# Generated by Django 5.0.2 on 2025-01-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_documents', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='election',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='election',
            name='elections_e_status_2b6bdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='election',
            name='elections_e_electio_88ab4e_idx',
        ),
        migrations.RemoveField(
            model_name='election',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='election',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='election',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='election',
            name='total_voters',
        ),
        migrations.RemoveField(
            model_name='election',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='election',
            name='voter_turnout',
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('PRESIDENTIAL', 'Presidential'), ('PARLIAMENTARY', 'Parliamentary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='requirement',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='elections.election'),
        ),
    ]
