# Generated by Django 5.0.2 on 2025-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_voter_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(default='initial', max_length=255),
            preserve_default=False,
        ),
    ]
